name: build-image
on: [push]
jobs:
  build-image:
    runs-on: self-hosted
    env:
      BUILDROOT_VERSION: 2021.11-rc1
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        path: microvmgen

    - id: cache
      name: Caching the download cache (should be fine), the ccache (might cause problems) as well as the host toolchain (might be a very bad idea)
      uses: actions/cache@v2
      with:
        key: buildroot-cache
        path: |
          buildroot/cache/dl
          buildroot/cache/ccache
          buildroot/output/host

    - uses: actions/checkout@v2
      with:
        repository: buildroot/buildroot
        path: buildroot
        ref: ${{ env.BUILDROOT_VERSION }}

    - name: Build all the things!
      working-directory: buildroot
      run: |
        BR2_EXTERNAL=../microvmgen make microvm_defconfig
        make -j$(nproc)

    - name: Upload the result
      uses: actions/upload-artifact@v2
      with:
        name: final-disk-image
        path: ./buildroot/output/images/disk.img
        if-no-files-found: error
